config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :users do
    resources :notegroups
  end

  resources :notegroups do
    resources :notes
    resources :members do
        patch 'accept'
        patch 'decline'
    end
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/member.rb
class Member < ApplicationRecord
  belongs_to :notegroup
  belongs_to :user
end

app/models/note.rb
class Note < ApplicationRecord
  belongs_to :notegroup
  belongs_to :user
  has_one_attached :photo

end

app/models/notegroup.rb
class Notegroup < ApplicationRecord
  belongs_to :user
  has_many :notes, dependent: :destroy
  has_many :members, dependent: :destroy
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :members, dependent: :destroy
  has_one_attached :photo, dependent: :destroy

  validates :photo, presence: true
  validates_uniqueness_of :name

  attr_writer :login

  def login
    @login || self.name || self.email
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?
    def configure_permitted_parameters
    # For additional fields in app/views/devise/registrations/new.html.erb
    # devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :email, :photo])

    devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :photo])

    # For additional in app/views/devise/registrations/edit.html.erb
    # devise_parameter_sanitizer.permit(:account_update, keys: [:username])
  end

  def default_url_options
    { host: ENV["DOMAIN"] || "localhost:3000" }
  end
end

app/controllers/members_controller.rb
class MembersController < ApplicationController
  def index
    @userc = User.all

    if params[:query].present?
      @users = User.where(name: params[:query])
      @notegroup = Notegroup.find(params[:notegroup_id])
      @members = @notegroup.members
    else
      @users = User.all
      @notegroup = Notegroup.find(params[:notegroup_id])
      @members = @notegroup.members
    end

  end

  # def new
  #   @member = Member.new
  #   @user = current_user
  #   @notegroup = Notegroup.find(params[:notegroup_id])

  # end
  def accept
   @member = Member.find(params[:member_id])
   @notegroup = @member.notegroup
   @member.status = "accept"
   @member.save!
   redirect_to notegroups_path
  end

  def decline
   @member = Member.find(params[:id])
   @notegroup = @member.notegroup
   @member.status = "decline"
   @member.save!
   redirect_to notegroups_path
  end

  def destroy
    @member = Member.find(params[:id])
    @notegroup = @member.notegroup
    @member.destroy
    redirect_to notegroups_path
  end

end

app/controllers/notegroups_controller.rb
class NotegroupsController < ApplicationController

  def index
    # @notes = Note.all
    @notegroups = Notegroup.all
    @users = User.all
    @members = Member.all

  end

  def show
    @user = User.find(params[:user_id])
    @members = Member.all
    @notegroup = Notegroup.find(params[:id])
    if params[:query].present?
      @users = User.where(name: params[:query])
    else
      @users = User.all
    end

    unless @member = Member.find_by(user: @user, notegroup: @notegroup)
      @member = Member.create(user: @user, notegroup: @notegroup, status: "waiting")
    end
  end

  def new
    @notegroup = Notegroup.new
    @user = current_user
    @note = Note.new
  end

  def create
    @notegroup = Notegroup.new(notegroup_params)
    @user = current_user
    @notegroup.user = @user
    if @notegroup.save
      redirect_to notegroups_path
    else
      render :new
    end
    @usergroup = Member.create(user:current_user, notegroup: @notegroup, status: "accept")
  end

  def edit
    @notegroup = Notegroup.find(params[:id])
  end

  def update
    @notegroup = Notegroup.find(params[:id])
    @notegroup.update(notegroup_params)
    redirect_to notegroups_path
  end

  def destroy
    @notegroup = Notegroup.find(params[:id])
    @user = @notegroup.user
    @notegroup.destroy
    redirect_to notegroups_path
  end

private

  def notegroup_params
    params.require(:notegroup).permit(:title, :color)
  end

end

app/controllers/notes_controller.rb
class NotesController < ApplicationController

  def new
    @note = Note.new
    @user = current_user
    @notegroup = Notegroup.find(params[:notegroup_id])
  end

  # def show
  #   @notegroup = Notegroup.find(params[:notegroup_id])
  #   @note = Note.find(params[:note_id])
  # end


  def create
    @notegroup = Notegroup.find(params[:notegroup_id])
    @note = Note.new(note_params)
    @note.notegroup = @notegroup
    @user = current_user
    @note.user = @user
    if @note.save
      redirect_to notegroups_path
    else
      render :new
    end
  end

  def edit
    @notegroup = Notegroup.find(params[:notegroup_id])
    @note = Note.find(params[:id])
  end

  def update
    @notegroup = Notegroup.find(params[:notegroup_id])
    @note = Note.find(params[:id])
    @note.update(note_params)
    redirect_to notegroups_path
  end

  def destroy
      @note = Note.find(params[:id])
      @note.destroy
      redirect_to notegroups_path
  end

private

  def note_params
    params.require(:note).permit(:title, :content, :date)
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [:home]

  def home
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    if params[:query].present?
      @users = User.where(name: params[:query])
    else
      @users = User.all
    end
  end

  def show
    @members = Member.all
    @user = User.find(params[:id].last)
    @notegroup = Notegroup.find(params[:id])


    unless @member = Member.find_by(user: @user, notegroup: @notegroup)
      @member = Member.create(user: @user, notegroup: @notegroup, status: "waiting")
    end

  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/meta_tags_helper.rb
module MetaTagsHelper
  def meta_title
    content_for?(:meta_title) ? content_for(:meta_title) : DEFAULT_META["meta_title"]
  end

  def meta_description
    content_for?(:meta_description) ? content_for(:meta_description) : DEFAULT_META["meta_description"]
  end

  def meta_image
    meta_image = (content_for?(:meta_image) ? content_for(:meta_image) : DEFAULT_META["meta_image"])
    # little twist to make it work equally with an asset or a url
    meta_image.starts_with?("http") ? meta_image : image_url(meta_image)
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title><%= meta_title %></title>
    <meta name="description" content="<%= meta_description %>">


    <!-- Facebook Open Graph data -->
    <meta property="og:title" content="<%= meta_title %>" />
    <meta property="og:type" content="website" />
    <meta property="og:url" content="<%= request.original_url %>" />
    <meta property="og:image" content="<%= meta_image %>" />
    <meta property="og:description" content="<%= meta_description %>" />
    <meta property="og:site_name" content="<%= meta_title %>" />

    <!-- Twitter Card data -->
    <meta name="twitter:card" content="summary_large_image">
    <meta name="twitter:site" content="<%= DEFAULT_META["twitter_account"] %>">
    <meta name="twitter:title" content="<%= meta_title %>">
    <meta name="twitter:description" content="<%= meta_description %>">
    <meta name="twitter:creator" content="<%= DEFAULT_META["twitter_account"] %>">
    <meta name="twitter:image:src" content="<%= meta_image %>">

    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="mobile-web-app-capable"  content="yes">
    <link rel="manifest" href="<%= asset_path 'manifest.json' %>">
    <%= render 'shared/ios_pwa_links' %>


    <%= csrf_meta_tags %>
    <%= favicon_link_tag "Logo noteit.png" %>
    <%= action_cable_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%#= stylesheet_pack_tag 'application', media: 'all' %> <!-- Uncomment if you import CSS in app/javascript/packs/application.js -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
    <link href="https://fonts.googleapis.com/css2?family=Damion&display=swap" rel="stylesheet">
  </head>
  <body>

    <%= render 'shared/flashes' %>
    <%= yield %>

    <%= javascript_pack_tag 'application' %>
  </body>
</html>

app/views/members/index.html.erb
<div class="fondcolor"> </div>


<div class="container">
  <% @userc.each do |user| %>
    <% if @notegroup.user == user %>
         <div class="member-chef" > <h2> Note'Chef : </h2> <%= cl_image_tag user.photo.key, class: 'avatar-member-chef' %> </div>
    <% end %>
  <% end %>
  <div class="members-team" >
    <h2> Note'Membres : </h2>
    <div class="member-team" >
      <% @notegroup.members.each do |member| %>
        <% if @members.count  <= 1 %>
          <p class="nothing"> aucun membres </p>
        <% else %>
          <% if member.user == @notegroup.user%>
          <% else %>
            <%= cl_image_tag member.user.photo.key, class: 'avatar-member' %>
          <% end %>
        <% end %>
      <% end %>
      <div class="member-add">
        <h2>Liste de tous les membres</h2>
         <div class="add-friend-order">
          <% @users.each do |user| %>
            <% if @notegroup.user != user %>
              <%= link_to user_notegroup_path(user, @notegroup), data: { confirm: "Voulez-vous vraiment ajouter cette personne ?" },class: "add-friend-link" do  %>
                <div class="add-friend-member">
                 <%=cl_image_tag user.photo.key, class: 'avatar-list' %>
                 <p class="friend-name"><%= user.name %></p>
                </div>
              <% end %>
            <% end %>
          <% end %>
        </div>
        <%= form_tag notegroup_members_path, method: :get do %>
          <%= text_field_tag :query,
            params[:query],
            class: "form-control search-bar-member",
            placeholder: "filtre par nom"
          %>
          <%= submit_tag "rechercher", class: "btn btn-primary membresearch" %>
        <% end %>

        <%= link_to notegroups_path do %>
          <i class="fas fa-home back-home-member"></i>
        <% end %>

      </div>
    </div>
  </div>
</div>

app/views/notegroups/edit.html.erb
<div class="fondcolor"> </div>

<div class="container">
  <div class="note-group">
    <div class="note-group-add">
      <h2>  </h2>
    </div>
    <div class="container form_new">
      <%= simple_form_for @notegroup do |f| %>
        <%= f.label "Titre de votre Note'Group" %>
        <%= f.text_field :title %>
        <br>
         <div class="colorthemebutton">
         <%= f.radio_button :color, ["thème1"] , class: "blueround", label: "haha"%>
         <div class="blueround"></div>
      </div>
      <div class="colorthemebutton">
         <%= f.radio_button :color, ["thème2"] , class: "redround", label: "haha"%>
         <div class="redround"></div>
      </div>
      <div class="colorthemebutton">
         <%= f.radio_button :color, ["thème3"] , class: "greenround", label: "haha"%>
         <div class="greenround"></div>
      </div>
    <br>

        <%= f.submit "Edition votre Note'Group", class: "button" %>
      <% end %>
    </div>
  </div>
  <%= link_to notegroups_path do %>
    <i class="fas fa-home back-home"></i>
  <% end %>
</div>

app/views/notegroups/index.html.erb
<div class="navbar">
  <i class="fas fa-calendar-alt calendar-nav"></i>
  <div class="avatar-group">
    <div class="avatar-deco">
      <% @members.where(user: current_user.id).each do |member| %>
        <% if member[:status] == "waiting" %>
          <i class="fas fa-plus-circle notif"></i>
        <% end %>
      <% end %>
      <%= cl_image_tag current_user.photo.key, class: "avatar avatarmenu" if current_user.photo.attached? %>
    </div>
  </div>
</div>

<div class="navbarbis"></div>

<div class="fondcolor"> </div>

<div class="dropdown-block">
  <% @members.where(user: current_user.id).each do |member| %>
    <% if member[:status] == "waiting" %>
      <!-- <i class="fas fa-plus-circle notif"></i> -->
      <div class="invitation">
        <h4>Note'Invitations</h4>
      </div>
      <i class="fas fa-plus-circle notif-2"></i>
    <% end %>
  <% end %>
  <h4><%= link_to "Mon profil", edit_user_registration_path(current_user), class: "dropdown-item deco"%></h4>
  <h4><%= link_to "Se déconnecter", destroy_user_session_path, method: :delete, class: "dropdown-item deco"%></h4>
</div>

<div class="invitation-block">
  <% @members.where(user: current_user.id).each do |member| %>
    <% if member[:status] == "waiting" %>
      <div class="invitation-block-update">
        <h2 class="status">Nouvelle demande pour <strong><%= member.notegroup.title %></strong> </h2>
        <h2 class="status">vous êtes invité par : <strong><%= member.notegroup.user.name %></strong> </h2>
        <div class="status-logo">
          <%= link_to notegroup_member_accept_path(member.notegroup, member), method: :patch do %>
            <i class="far fa-check-circle accept"></i>
          <% end %>
          <%= link_to notegroup_member_path(member.notegroup, member), method: :delete, data: { confirm: 'Voulez-vous vraiment décliner cette invitation ?' } do %>
            <i class="far fa-times-circle decline"></i>
          <% end %>
        </div>
      </div>
    <% end %>
  <% end %>
</div>

<div class="calendar">
   <div class="month">
    <ul>
      <li class="prev" id="prev">&#10094;</li>
      <li class="next" id="next">&#10095;</li>
      <li id="month"><br><!-- <span style="font-size:18px"><%#= Date.today.year %></span> --></li>
      <li id="year"><br><!-- <span style="font-size:18px"><%#= Date.today.year %></span> --></li>
    </ul>
  </div>

  <ul class="weekdays">
    <li>Lu</li>
    <li>Ma</li>
    <li>Me</li>
    <li>Je</li>
    <li>Ve</li>
    <li>Sa</li>
    <li>Di</li>
  </ul>
  <ul class="days" id="days">

  </ul>

  <div class="detailsday">

  </div>

  </div>

<div class="add-notegroup">
  <!-- <h4>Créer un Note'Group</h4> -->
  <%= link_to new_notegroup_path do %>
    <i class="fas fa-plus-square"></i>
  <% end %>
</div>


<div class="container index">
  <div class="row justify-content-center">
    <% @notegroups.each_with_index do |notegroup, index| %>
      <% notegroup.members.each do |member| %>
        <% if current_user == member.user && member.status == "accept"%>
          <div class="col-12 col-lg-4">
            <div class="note-card-blank">
              <div class="note-card-blank-fond">
                <% if notegroup.color == 'thème1' %>
                  <div class="notes-title-blue notes-title<%= index %>">
                <% elsif notegroup.color == 'thème2' %>
                  <div class="notes-title-red notes-title<%= index %>">
                <% elsif notegroup.color == 'thème3' %>
                  <div class="notes-title-green notes-title<%= index %>">
                <% end %>
                    <div class="notes-header">
                      <% if current_user == notegroup.user %>
                      <div class="note-edit">
                        <%= link_to notegroup_path(notegroup), method: :delete, data: { confirm: 'Voulez-vous vraiment supprimer ce groupe ?' }, class: "del-group" do%>
                          <i class="fas fa-trash-alt"></i>
                        <% end %>
                        <%= link_to edit_notegroup_path(notegroup) do%>
                          <i class="fas fa-edit edit-note"></i>
                        <% end %>
                      </div>
                      <% else %>
                        <%= link_to notegroup_member_path(member.notegroup, member), method: :delete, data: { confirm: 'Voulez-vous vraiment quitter ce notegroup ?' } do %>
                          <i class="fas fa-ban"></i>
                        <% end %>
                      <% end %>
                      <h2><%= notegroup.title.capitalize%></h2>
                      <div class="note-member-add">
                        <%= link_to notegroup_members_path(notegroup, @members) do %>
                            <i class="fas fa-user-plus"></i>
                          <% end %>
                        <%= link_to new_notegroup_note_path(notegroup), class: "add-note" do%>
                          <i class="fas fa-plus-circle"></i>
                        <% end %>
                      </div>
                    </div>

                    <div class="member-position">
                      <% notegroup.members.each do |member| %>
                        <% if notegroup.user == member.user %>
                          <i class="fas fa-crown"></i>
                          <%= cl_image_tag member.user.photo.key, class: 'avatar-note-chef' %>
                        <% else %>
                          <% if member.status == "waiting"%>
                            <%= cl_image_tag member.user.photo.key, class: 'avatar-note-waiting' %>
                            <div class="explain-waiting">
                              <p>En attente de validation par <%= member.user.name %> </p>
                            </div>
                          <% else %>
                            <%= cl_image_tag member.user.photo.key, class: 'avatar-note' %>
                          <% end %>
                        <% end %>
                      <% end %>
                    </div>
                    <div class="flechedown flechedown<%= index %>"><i class="arrow down"></i></div>
                    <div class="flecheup flecheup<%= index %>"><i class="arrow up"></i></div>
                  </div>



              <div class="note-group-item note-group-item<%= index %>">
                <% if notegroup.notes.count <=0 %>
                    <p class="noteless">aucune note</p>
                <% else %>
                <% notegroup.notes.order(date: :asc).each do |note| %>
                    <div class="my-note-space">
                      <h3 class="note-title"> <%= note.title%> </h3>
                      <!-- <p class="note-date"> <%= note.date%> jours </p> -->
                      <% @time = (note.date - Date.today).to_i %>
                      <% if current_user == note.user %>
                      <div class="note-edit">
                        <%= link_to edit_notegroup_note_path(notegroup, note) do%>
                            <i class="fas fa-edit edit-note"></i>
                          <% end %>
                        <%= link_to notegroup_note_path(notegroup, note), method: :delete, data: { confirm: 'Voulez-vous vraiment supprimer cette note ?' } do%>
                            <i class="fas fa-trash-alt poubellenote"></i>
                          <% end %>
                      </div>
                      <% end %>
                    </div>

                    <div class="my-note-content">
                      <div class="my-note-space-2">
                        <p class="note-content"> <%= note.content%> </p>
                      </div>
                      <div class="my-note-space-3">
                        <%= cl_image_tag note.user.photo.key, class: 'avatar-note'%>
                        <div class="date-done">
                          <% if note.done == false %>
                            <!-- <i class="fas fa-times note-done-false"></i> -->
                          <% else %>
                            <!-- <i class="far fa-check-circle note-done-true"></i> -->
                          <% end %>
                          <% if @time >= 1 %>
                           <p class="note-date-green"> il reste <%= (note.date - Date.today).to_i %> jours </p>
                           <p id="testdate" > <%= note.date %> </p>
                          <% elsif @time == 0 %>
                            <p class="note-date-red"> Expire aujourd'hui </p>
                            <p id="testdate" > <%= note.date %> </p>
                          <% else %>
                            <p class="note-date-red"> A expiré depuis <%= (Date.today - note.date).to_i %> <% if @time == -1  %> jour <% else %> jours <% end %></p>
                            <p id="testdate" > <%= note.date %> </p>
                          <% end %>
                        </div>
                      </div>
                    </div>


                    <div class="bordernote"></div>

                <% end %>
                <% end %>
                </div>


              </div>
            </div>
          </div>
        <% end %>
      <% end %>
    <% end %>
  </div>
</div>

app/views/notegroups/new.html.erb
<div class="fondcolor"> </div>

<div class="container">
  <div class="note-group">
    <div class="note-group-add">
      <h2>Nouveau Note'Group</h2>
    </div>
    <div class="container form_new">

      <%= simple_form_for @notegroup do |f| %>
        <%= f.input :title, placeholder: "Titre de votre Note'Group",  label: false  %>


      <div class="colorthemebutton">
         <%= f.radio_button :color, ["thème1"] , class: "blueround", label: "haha"%>
         <div class="blueround"></div>
      </div>
      <div class="colorthemebutton">
         <%= f.radio_button :color, ["thème2"] , class: "redround", label: "haha"%>
         <div class="redround"></div>
      </div>
      <div class="colorthemebutton">
         <%= f.radio_button :color, ["thème3"] , class: "greenround", label: "haha"%>
         <div class="greenround"></div>
      </div>


        <%#= f.collection_radio_buttons :color, [["thème1", class: "blueround"] , ["thème2", class: "redround"] , ["thème3", class: "greenround"]], :first, :last , label: "haha"%>
        <%#= f.input :color, collection: [["thème1", class: "blueround"] , ["thème2", class: "redround"] , ["thème3", class: "greenround"] ], label: "Choissisez un thème", class: "colorinput", required: true, selected: "thème1"%>
      <br>
        <%= f.submit "Créer votre Note'Group", class: "button notebuttonadd" %>
      <% end %>
    </div>
  </div>
  <%= link_to notegroups_path do %>
    <i class="fas fa-home back-home"></i>
  <% end %>
</div>

app/views/notegroups/show.html.erb
<div class="fondcolor"> </div>

<div class="container">
  <div class="note-group">
    <div class="note-group-add">
      <h2>Vous venez d'envoyer un demande à <%= @user.name.capitalize %></h2>
      <p>Une notification lui sera envoyé pour intégrer le groupe : <strong><%= @notegroup.title %></strong></p>
      <%= link_to "retour à l'acceuil", notegroups_path, class: 'btn btn-primary membresearch' %>
    </div>
  </div>
</div>

app/views/notes/edit.html.erb
<div class="fondcolor"> </div>


  <div class="note">
      <div class="note-add-title">
        <h2>Editez votre Note</h2>
      </div>
        <div class="form_new form_edit">
          <div class="container">
           <%= simple_form_for [@notegroup , @note ] do |f| %>
            <%= f.input :title, placeholder: "Titre de votre Note (optionnel)", label: false %>
            <%= f.input :content, placeholder: "Description de votre Note",  label: false %>
          </div>
          <div class="form_edit">
            <%= f.input :date, label: "Quand doit se terminer votre Note?" %>
          </div>
          <%= f.submit "Créer votre Note", class: "button notebuttonadd" %>
        <% end %>
      </div>
  </div>
  <%= link_to notegroups_path do %>
    <i class="fas fa-home back-home-note "></i>
  <% end %>

app/views/notes/new.html.erb
<div class="fondcolor"> </div>

<div class="container">
  <div class="note">
      <div class="note-add-title">
        <h2>Nouvelle note</h2>
      </div>
        <div class="container form_new">
         <%= simple_form_for [@notegroup , @note ] do |f| %>
          <%= f.input :title, placeholder: "Titre de votre Note (optionnel)", label: false %>
          <%= f.input :content, placeholder: "Description de votre Note",  label: false %>
          <%= f.input :date, label: "Quand doit se terminer votre Note?" %>
          <%= f.submit "Créer votre Note", class: "button notebuttonadd" %>
        <% end %>
      </div>
  </div>
  <%= link_to notegroups_path do %>
    <i class="fas fa-home back-home-note "></i>
  <% end %>
</div>

app/views/pages/home.html.erb
<div class="fondcolor">
  <div class="home_logo">
    <a href="#">
     <!--  <div class="row justify-content-center">
          <div class="col-4 col-xs-10"> -->
            <%= link_to notegroups_path do%>
              <img class="logo-home" src="https://res.cloudinary.com/dc9pm7uj8/image/upload/v1589230080/note_logo_oy9nef.png" alt="logo">
            <% end %>
<!--           </div>
      </div> -->
    </a>
  </div>
  <div class="title-home">
    <h1>Note'it</h1>
  </div>
</div>

app/views/shared/_cards.html.erb
<div class="notes-title-red notes-title<%= index %>">
                    <div class="notes-header">
                      <% if current_user == notegroup.user %>
                        <%= link_to notegroup_path(notegroup), method: :delete, data: { confirm: 'Voulez-vous vraiment supprimer ce groupe ?' }, class: "del-group" do%>
                          <i class="fas fa-trash-alt"></i>
                        <% end %>
                      <% else %>
                        <%= link_to notegroup_member_path(member.notegroup, member), method: :delete, data: { confirm: 'Voulez-vous vraiment quitter ce notegroup ?' } do %>
                          <i class="fas fa-ban"></i>
                        <% end %>
                      <% end %>
                      <h2><%= notegroup.title.capitalize%></h2>
                      <div class="note-member-add">
                        <%= link_to notegroup_members_path(notegroup, @members) do %>
                            <i class="fas fa-user-plus"></i>
                          <% end %>
                        <%= link_to new_notegroup_note_path(notegroup), class: "add-note" do%>
                          <i class="fas fa-plus-circle"></i>
                        <% end %>
                      </div>
                    </div>

                    <div class="member-position">
                      <% notegroup.members.each do |member| %>
                        <% if notegroup.user == member.user %>
                          <i class="fas fa-crown"></i>
                          <%= cl_image_tag member.user.photo.key, class: 'avatar-note-chef' %>
                        <% else %>
                          <% if member.status == "waiting"%>
                            <%= cl_image_tag member.user.photo.key, class: 'avatar-note-waiting' %>
                            <div class="explain-waiting">
                              <p>En attente de validation par <%= member.user.name %> </p>
                            </div>
                          <% else %>
                            <%= cl_image_tag member.user.photo.key, class: 'avatar-note' %>
                          <% end %>
                        <% end %>
                      <% end %>
                    </div>
                  </div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

app/views/shared/_ios_pwa_links.html.erb
<link rel="apple-touch-icon" sizes="57x57" href="<%= image_path 'icons/apple-icon-57x57.png' %>">
<link rel="apple-touch-icon" sizes="60x60" href="<%= image_path 'icons/apple-icon-60x60.png' %>">
<link rel="apple-touch-icon" sizes="72x72" href="<%= image_path 'icons/apple-icon-72x72.png' %>">
<link rel="apple-touch-icon" sizes="76x76" href="<%= image_path 'icons/apple-icon-76x76.png' %>">
<link rel="apple-touch-icon" sizes="114x114" href="<%= image_path 'icons/apple-icon-114x114.png' %>">
<link rel="apple-touch-icon" sizes="120x120" href="<%= image_path 'icons/apple-icon-120x120.png' %>">
<link rel="apple-touch-icon" sizes="144x144" href="<%= image_path 'icons/apple-icon-144x144.png' %>">
<link rel="apple-touch-icon" sizes="152x152" href="<%= image_path 'icons/apple-icon-152x152.png' %>">
<link rel="apple-touch-icon" sizes="180x180" href="<%= image_path 'icons/apple-icon-180x180.png' %>">
<link rel="icon" type="image/png" sizes="32x32" href="<%= image_path 'icons/favicon-32x32.png' %>">
<link rel="icon" type="image/png" sizes="96x96" href="<%= image_path 'icons/favicon-96x96.png' %>">
<link rel="icon" type="image/png" sizes="16x16" href="<%= image_path 'icons/favicon-16x16.png' %>">